version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data:/var/lib/mysql
  redis:
    image: redis:latest
    command: redis-server --requirepass admin --port 6379
    container_name: redis
    volumes:
      - ./db/redis/data:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379