spring:
  profiles:
    active: default
  datasource: # 동일한 DB이지만 마스터-슬레이브 구조로 설정해본다.
    master:
      jdbc-url: jdbc:mysql://localhost:3306/testbed
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/testbed
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false # DDL 생성 여부
    hibernate:
      ddl-auto: validate # validate -> 엔티티 클래스와 테이블이 정상적으로 매핑되는지만 검사한다
    show-sql: true
    properties:
      hibernate:
        format_sql: true # sql을 보기 좋게 출력
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        default_batch_fetch_size: 1000
  flyway:
    enabled: false